services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow
    command: >
      mlflow server 
        --backend-store-uri sqlite:///mlflow/data.db
        --host "0.0.0.0" 
        --port 5000
    ports:
      - "5000:5000"
    volumes:
      - mlflow-runs:/mlruns
      - mlflow-artifacts:/mlartifacts
      - mlflow-db:/mlflow
    environment:
      # insecure setting, for didactical purposes only
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
volumes:
  mlflow-runs:
  mlflow-artifacts:
  mlflow-db:
